FROM ubuntu:22.04

RUN mkdir -p /home/georgii
RUN echo "Hello, Georgii!" > /home/georgii/hello.txt
RUN echo "Hello, Georgii2!" > /home/georgii/hello2.txt
RUN rm /home/georgii/hello.txt
RUN mkdir -p /home/georgii/dir1
RUN echo "Hello, Georgii from dir1!" > /home/georgii/dir1/hello.txt
RUN rm -rf /home/georgii/dir1
